apps/units/urls.py
from django.conf.urls import patterns, include, url
from apps.units import views
from django.contrib import admin


urlpatterns = patterns('',


    url(r'^admin/', include(admin.site.urls)),
    url(r'^main$', views.MainView.as_view()),
    url(r'^about$', views.AboutView.as_view()),

)

gisc2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


api_patterns = patterns('',
    url(r'^', include('apps.units.api_urls'), name='units'),
    url(r'^', include('apps.units.api_urls'), name='counties'),
    url(r'^', include('apps.world.api_urls'), name='world'),
)

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.units.urls', namespace='units')),
    url(r'api/v1/', include(api_patterns, namespace='api')),
)

apps/units/models.py
from django.contrib.gis.db import models


class Unit(models.Model):
    """Add Docstring"""
    name = models.CharField(max_length=40)
    status = models.BooleanField()
    desc = models.CharField(max_length=280)

    def __str__(self):
        return "{}".format(self.name)


class County(models.Model):
    """Represents a US County."""
    name = models.CharField(max_length=60)
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return "{}".format(self.name)

apps/units/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.


class MainView(generic.TemplateView):
    """Loads the main page"""
    template_name = 'units/main.html'


class AboutView(generic.TemplateView):
    template_name = 'units/about.html'

apps/units/templates/units/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}About{% endblock %}
{% block mapbox %}
    <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.css' rel='stylesheet'/>
    <style> #map {position:absolute; top:52px; right:10px; left:0; bottom:0; width:100%; height:400px;}</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div id="map"></div>
        </div>
    </div>
</div>
{% endblock %}
{% block morescripts %}
    <script>
    var map = L.mapbox.map('map', 'nwalk.jljei9kn');
    var county_style = {
        color: "yellow",
        weight: 2,
        opacity: 1,
        fillOpacity: 0.75
    };
    $.getJSON("{%  url 'api:counties' %}", function (data) {
        L.geoJson(data, {style: county_style,
            onEachFeature: function (feature, layer) {
                (function (layer, properties) {
                    layer.on("click", function (e) {
                        var popup = L.popup().setLatLng(e.latlng)
                                .setContent('<a href="http://www.google.com">' + properties.name + '</a>')
                                .openOn(map);
                    });
            }) (layer, feature.properties);
    }}).addTo(map);
    })
    </script>
{% endblock %}

apps/units/templates/units/main.html
{% extends 'base.html' %}
{% load staticfiles %}

<body>
{% block carousel %}
    <div class="carousel slide" id="carousel-992047">
        <ol class="carousel-indicators">
            <li data-slide-to="0" data-target="#carousel-992047">
            </li>
            <li data-slide-to="1" data-target="#carousel-992047" class="active">
            </li>
            <li data-slide-to="2" data-target="#carousel-992047">
            </li>
        </ol>
        <div class="carousel-inner">
            <div class="item">
                <img alt="" src="http://lorempixel.com/1600/500/sports/1" />
                <div class="carousel-caption">
                    <h4>
                        First Thumbnail label
                    </h4>
                    <p>
                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                    </p>
                </div>
            </div>
            <div class="item active">
                <img alt="" src="http://lorempixel.com/1600/500/sports/2" />
                <div class="carousel-caption">
                    <h4>
                        Second Thumbnail label
                    </h4>
                    <p>
                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                    </p>
                </div>
            </div>
            <div class="item">
                <img alt="" src="http://lorempixel.com/1600/500/sports/3" />
                <div class="carousel-caption">
                    <h4>
                        Third Thumbnail label
                    </h4>
                    <p>
                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                    </p>
                </div>
            </div>
        </div> <a class="left carousel-control" href="#carousel-992047" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-992047" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div> <address> <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890</address>
    <div class="jumbotron">
        <h1>
            Hello, world!
        </h1>
        <p>
            This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
        </p>
        <p>
            <a class="btn btn-primary btn-large" href="#">Learn more</a>
        </p>
    </div>
    <a id="modal-862784" href="#modal-container-862784" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
    <div class="modal fade" id="modal-container-862784" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Modal title
                    </h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
<div class="row clearfix">
    <div class="col-md-4 column">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Product
                    </th>
                    <th>
                        Payment Taken
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        1
                    </td>
                    <td>
                        TB - Monthly
                    </td>
                    <td>
                        01/04/2012
                    </td>
                    <td>
                        Default
                    </td>
                </tr>
                <tr class="active">
                    <td>
                        1
                    </td>
                    <td>
                        TB - Monthly
                    </td>
                    <td>
                        01/04/2012
                    </td>
                    <td>
                        Approved
                    </td>
                </tr>
                <tr class="success">
                    <td>
                        2
                    </td>
                    <td>
                        TB - Monthly
                    </td>
                    <td>
                        02/04/2012
                    </td>
                    <td>
                        Declined
                    </td>
                </tr>
                <tr class="warning">
                    <td>
                        3
                    </td>
                    <td>
                        TB - Monthly
                    </td>
                    <td>
                        03/04/2012
                    </td>
                    <td>
                        Pending
                    </td>
                </tr>
                <tr class="danger">
                    <td>
                        4
                    </td>
                    <td>
                        TB - Monthly
                    </td>
                    <td>
                        04/04/2012
                    </td>
                    <td>
                        Call in to confirm
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="row clearfix">
            <div class="col-md-12 column">
                <h3>
                    h3. Lorem ipsum dolor sit amet.
                </h3>
            </div>
        </div>
    </div>
    <div class="col-md-4 column">
        <blockquote class="pull-right">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
            </p> <small>Someone famous <cite>Source Title</cite></small>
        </blockquote> <button type="button" class="btn btn-success">Default</button>
    </div>
    <div class="col-md-4 column">
        <div class="tabbable" id="tabs-819002">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#panel-719771" data-toggle="tab">Section 1</a>
                </li>
                <li>
                    <a href="#panel-349485" data-toggle="tab">Section 2</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="panel-719771">
                    <p>
                        I'm in Section 1.
                    </p>
                </div>
                <div class="tab-pane" id="panel-349485">
                    <p>
                        Howdy, I'm in Section 2.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% block title %}
    <title>Main Page</title>
    {% endblock %}
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
{% block mapbox %}{% endblock %}
</head>
<body>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-static-top" role="navigation">
                {% block carousel %}{% endblock %}
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="#">Link</a>
						</li>
						<li>
							<a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Action</a>
								</li>
								<li>
									<a href="#">Another action</a>
								</li>
								<li>
									<a href="#">Something else here</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">Separated link</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">One more separated link</a>
								</li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" />
						</div> <button type="submit" class="btn btn-default">Submit</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Action</a>
								</li>
								<li>
									<a href="#">Another action</a>
								</li>
								<li>
									<a href="#">Something else here</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">Separated link</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>

			</nav>
        </div>
    </div>
{% block content %}{% endblock %}
</div>
{% block morescripts %}{% endblock %}
</body>
</html>